'use client';
import { useEffect, useRef, useState } from 'react';
import { emptyTournament, type LocalTournament } from '../../core/privateTournament.ts';
import { formatDateInput, isCompleteDate } from '../../core/dateInput.ts';
import { encryptPayload, decryptPayload, readPrivateEvent, writePrivateEvent } from '../lib/privateStore.ts';
import { getOperatorKey } from '../lib/config.ts';
import { safeGoogleRules, RULE_HEADERS } from '../../core/safeGoogleRules.ts';

import { useSetupDraft } from '../lib/useSetupDraft.ts';
import { validDraft, type SetupDraft } from '../../core/setupDraft.ts';

const steps=['大会を決める','選手を募集','保存を確認','選手を読む','対戦を作る','リンクを渡す'];
export default function Setup() {
  const [events,setEvents]=useState<Array<{eventId:string;title:string;date:string}>>([]);
  const [draftEvents,setDraftEvents]=useState<Array<{eventId:string;title:string;date:string}>>([]);
  const importedControls=useRef<string|null>(null);
  const [step,setStep]=useState(1);
  const [data,setData]=useState<LocalTournament|null>(null);
  const [event,setEvent]=useState('');
  const [message,setMessage]=useState('');
  const [busy,setBusy]=useState(false);
  const [connected,setConnected]=useState(false);
  const [saved,setSaved]=useState(false);
  const [entryCode,setEntryCode]=useState('');
  const [rounds,setRounds]=useState(3),[roundSeconds,setRoundSeconds]=useState(180),[breakSeconds,setBreakSeconds]=useState(60);
  const draft=useSetupDraft(data,{rounds,roundSeconds,breakSeconds});
  const [handoffPassword,setHandoffPassword]=useState('');
  const [handoffMessage,setHandoffMessage]=useState('');
  const applyDraft=(value:SetupDraft)=>{
    importedControls.current=value.document.eventId;setData(value.document);setEvent(value.document.eventId);setRounds(value.controls.rounds);setRoundSeconds(value.controls.roundSeconds);setBreakSeconds(value.controls.breakSeconds);setSaved(false);draft.resume();
    const url=new URL(location.href);url.searchParams.set('event',value.document.eventId);history.replaceState(null,'',url);
    setMessage('途中保存を開きました。公開中の大会はまだ変えていません。');
  };
  const exportHandoff=async()=>{
    if(!data)return;
    try{const pack:SetupDraft={format:'tournament-os-draft-1',revision:0,document:data,controls:{rounds,roundSeconds,breakSeconds}};
      if(!validDraft(pack,data.eventId))throw new Error('引継ぎ内容を確認してください。');
      const text=await encryptPayload(pack,handoffPassword),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='TournamentOS-引継ぎ-'+data.eventId+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setHandoffMessage('引継ぎファイルを作りました。製作者にファイルを渡し、合言葉は別に伝えてください。');
    }catch(error){setHandoffMessage(error instanceof Error?error.message:'ファイルを作れません。');}
  };
  const importHandoff=async(file:File)=>{
    try{if(file.size>12*1024*1024)throw new Error('ファイルが大きすぎます。');const value=await decryptPayload(await file.text(),handoffPassword);
      if(!value||typeof value!=='object'||!validDraft(value,(value as SetupDraft).document?.eventId))throw new Error('引継ぎファイルではありません。');
      if(!confirm('現在の入力を引継ぎファイルに切り替えます。公開中の大会は変えません。よろしいですか？'))return;
      applyDraft(value);setHandoffMessage('引継ぎ内容を開きました。確認してから大会を保存してください。');
    }catch{setHandoffMessage('開けませんでした。合言葉とファイルを確認してください。今の入力は残しています。');}
  };
  useEffect(()=>{if(importedControls.current===data?.eventId){importedControls.current=null;return;}importedControls.current=null;const rule=data?.schedule?.[0];if(rule){setRounds(rule.rounds);setRoundSeconds(rule.roundSeconds);setBreakSeconds(rule.breakSeconds);}},[data?.eventId]);
  useEffect(()=>{if(!data)return;fetch('/api/private-recruitment?event='+encodeURIComponent(data.eventId),{headers:{'x-operator-key':getOperatorKey()},cache:'no-store'}).then(r=>r.json()).then((body:unknown)=>{const result=body as {ok?:boolean;code?:string};setEntryCode(result.ok?result.code||'':'');}).catch(()=>setEntryCode(''));},[data?.eventId]);
  useEffect(()=>{
    const url=new URL(location.href);url.searchParams.set('storage','cloud');history.replaceState(null,'',url);
    const id=url.searchParams.get('event')||'my-tournament';setEvent(id);
    fetch('/api/private-events',{headers:{'x-operator-key':getOperatorKey()},cache:'no-store'}).then(r=>r.json()).then((body:unknown)=>{const list=body as {ok?:boolean;events?:Array<{eventId:string;title:string;date:string}>};if(list.ok&&Array.isArray(list.events))setEvents(list.events);}).catch(()=>undefined);
    fetch('/api/private-drafts',{headers:{'x-operator-key':getOperatorKey()},cache:'no-store'}).then(r=>r.json()).then((body:unknown)=>{const list=body as {ok?:boolean;events?:Array<{eventId:string;title:string;date:string}>};if(list.ok&&Array.isArray(list.events))setDraftEvents(list.events);}).catch(()=>undefined);
    readPrivateEvent(id).then(value=>{setData(value??emptyTournament(id));setConnected(true);setSaved(Boolean(value));}).catch(()=>setMessage('クラウドへ接続できません。管理者の接続を確認してください。データを移したり消したりしていません。'));
  },[]);
  const link=(path:string)=>path+'?event='+encodeURIComponent(data?.eventId||event)+'&storage=cloud';
  const open=async(copy=false,chosen=event)=>{
    if(!/^[a-z0-9][a-z0-9-]{0,63}$/.test(chosen))return setMessage('大会コードは半角英数字とハイフンで入力してください。');
    setBusy(true);
    try{const value=await readPrivateEvent(chosen);setEvent(chosen);setData(value??emptyTournament(chosen));setConnected(true);setSaved(Boolean(value));setMessage(value?'保存した大会を開きました。':'新しい大会です。');if(copy&&value){const id='event-'+Date.now();setData({...emptyTournament(id),title:value.title+'（新しい大会）',venue:value.venue,date:value.date,entryConfig:value.entryConfig,schedule:value.schedule,recruitment:value.recruitment?{...value.recruitment,open:false,deadline:''}:undefined,audience:{open:false}});setEvent(id);setSaved(false);setMessage('前回の基本設定を使います。名簿と写真は複製していません。');}}catch{setMessage('大会を開けません。既存のデータは変えていません。');}finally{setBusy(false);}
  };
  const save=async()=>{
    if(!data)return;
    if(!data.title.trim()||!isCompleteDate(data.date))return setMessage('大会名と開催日を確認してください。');
    setBusy(true);try{const value=await writePrivateEvent({...data,date:formatDateInput(data.date)});setData(value);setSaved(true);const url=new URL(location.href);url.searchParams.set('event',value.eventId);history.replaceState(null,'',url);setEvents(old=>[{eventId:value.eventId,title:value.title,date:value.date},...old.filter(item=>item.eventId!==value.eventId)]);setMessage('クラウドに保存しました。');}catch(error){setMessage(error instanceof Error?error.message:'保存結果を確認できません。入力は残しています。');}finally{setBusy(false);}
  };
  const importRules=async()=>{
    setBusy(true);try{const result=await fetch('/api/private-rules?event='+encodeURIComponent(data!.eventId),{headers:{'x-operator-key':getOperatorKey()},cache:'no-store'});const body=await result.json() as {ok?:boolean;reason?:string;rules?: Array<{no:number;rounds:number;roundSeconds:number;breakSeconds:number}>};if(!result.ok||!body.ok)throw new Error(body.reason||'大会設定表を確認してください。');const schedule=safeGoogleRules([RULE_HEADERS,...(body.rules||[]).map((r:{no:number;rounds:number;roundSeconds:number;breakSeconds:number})=>[r.no,r.rounds,r.roundSeconds,r.breakSeconds])]);setData({...data!,schedule});setSaved(false);setMessage(schedule.length+'試合の時間設定を読み込みました。保存してください。氏名・写真・連絡先はGoogleから取得していません。');}catch(error){setMessage(error instanceof Error?error.message:'Googleに接続できません。');}finally{setBusy(false);}
  };
  const go=(number:number)=>{setStep(number);document.getElementById('setup-'+number)?.scrollIntoView({behavior:'smooth',block:'start'});};
  const field='mt-2 block min-h-14 w-full rounded-xl border-2 border-slate-300 p-3 text-lg focus:border-indigo-600 focus:outline-none';
  return <main className="min-h-screen bg-slate-50 p-4 pb-44 text-lg text-slate-950"><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-black">大会を作る</h1><p className="mt-3 text-slate-600">この一画面で設定できます。まず大会名・開催日・会場を入れて、下の保存ボタンを押してください。</p><aside aria-label="次にすること" className="mt-5 rounded-2xl border-2 border-indigo-200 bg-indigo-50 p-5"><b>次にすること</b><p className="mt-2">{!connected?"保存先への接続を確認しています。接続できるまで入力は始めません。":!saved?"変更した内容を確認して、下の「大会をクラウドに保存する」を押してください。":!data?.fighters.length?"保存できました。「名簿と写真を登録する」から選手を登録しましょう。":!data.bouts.length?"選手を登録できました。「対戦カードを作る」を開きましょう。":"準備した内容を確認し、「大会当日の画面を開く」へ進みましょう。"}</p></aside><section aria-label="途中保存と引継ぎ" className="mt-5 rounded-2xl border-2 border-emerald-200 bg-white p-5"><h2 className="text-2xl font-black">途中でやめても大丈夫</h2><p role="status" aria-label="途中保存の状態" className="mt-3">{draft.status}</p><p className="mt-2">途中保存では募集や観客公開は変わりません。</p>{draftEvents.length>0&&<details className="mt-3"><summary>ほかの大会の途中保存を開く</summary>{draftEvents.map(item=><button key={item.eventId} className="mt-2 block min-h-14 w-full rounded-xl border p-3 text-left" onClick={()=>{if(confirm('今の入力を切り替えます。必要なら先に引継ぎファイルを作ってください。'))location.href='/setup/?storage=cloud&event='+encodeURIComponent(item.eventId);}}>{item.title||'名前を入力する前の大会'} {item.date}</button>)}</details>}{draft.candidate&&<button onClick={()=>{if(confirm('現在の入力を途中保存の内容に切り替えますか？'))applyDraft(draft.candidate!);}} className="mt-3 min-h-14 rounded-xl bg-emerald-700 p-3 font-bold text-white">続きから開く</button>}<button disabled={!data} onClick={()=>{if(draft.candidate){if(confirm('今の入力で途中保存を更新しますか？'))draft.resume();}else void draft.retry();}} className="mt-3 ml-2 min-h-14 rounded-xl border p-3">途中保存を確認・更新する</button><details className="mt-4"><summary className="font-bold">困ったら製作者に引き継ぐ</summary><p className="mt-3">入力途中の設定・名簿・写真・対戦カードを暗号化してファイルにします。連絡先やログイン情報は含めません。自動送信はしません。</p><label className="mt-3 block">引継ぎの合言葉（10文字以上）<input type="password" autoComplete="new-password" className={field} value={handoffPassword} onChange={e=>setHandoffPassword(e.target.value)}/></label><button disabled={!data||handoffPassword.length<10} onClick={()=>void exportHandoff()} className="mt-3 min-h-14 rounded-xl bg-indigo-700 p-3 font-bold text-white disabled:bg-slate-300">製作者に渡すファイルを作る</button><label className="mt-4 block">製作者：受け取ったファイルを開く<input type="file" accept=".json" className={field} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void importHandoff(file);}}/></label>{handoffMessage&&<p role="status" className="mt-3">{handoffMessage}</p>}</details></section><nav className="my-5 flex flex-wrap gap-2" aria-label="大会作りの道順">{steps.map((name,i)=><button key={name} onClick={()=>go(i+1)} className={'min-h-14 rounded-xl border p-3 '+(step===i+1?'bg-indigo-700 text-white':'bg-white')}>{i+1}. {name}</button>)}</nav><div className="space-y-5">
  <section id="setup-1" className="scroll-mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">1. 大会を決める</h2><button disabled={!connected||busy} onClick={()=>{if(events.length){void open(true,events[0].eventId);return;}const id='event-'+Date.now();setEvent(id);setData({...emptyTournament(id),title:''});setSaved(false);setMessage('大会名・開催日・会場を入力してください。');}} className="mt-4 rounded-xl bg-emerald-700 p-3 font-black text-white disabled:bg-slate-300">新しい大会を作る</button>{events.length>0&&<label className="mt-4 block font-bold">保存した大会<select className={field} value={events.some(item=>item.eventId===event)?event:''} onChange={e=>setEvent(e.target.value)}><option value="">大会を選んでください</option>{events.map(item=><option key={item.eventId} value={item.eventId}>{item.title} {item.date}</option>)}</select></label>}<details className="mt-4"><summary>大会コードを確認・指定する（通常は操作不要）</summary><label className="mt-3 block font-bold">大会コード<input className={field} value={event} onChange={e=>setEvent(e.target.value.normalize('NFKC').toLowerCase())}/></label></details><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void open()} className="rounded-xl border p-3">保存した大会を開く／新しく作る</button><button disabled={busy} onClick={()=>void open(true,events.some(item=>item.eventId===event)?event:events[0]?.eventId||event)} className="rounded-xl border p-3">前の大会の設定を使う</button></div>{data&&<><label className="mt-4 block font-bold">大会名<input className={field} value={data.title} onChange={e=>{setData({...data,title:e.target.value});setSaved(false);}}/></label><label className="mt-4 block font-bold">開催日<input inputMode="numeric" className={field} value={data.date} placeholder="例: 20271003" onChange={e=>{setData({...data,date:e.target.value.normalize('NFKC')});setSaved(false);}} onBlur={e=>setData({...data,date:formatDateInput(e.target.value)})}/></label><label className="mt-4 block font-bold">会場<input className={field} value={data.venue} onChange={e=>{setData({...data,venue:e.target.value});setSaved(false);}}/></label></>}</section>
  {data&&<section id="setup-2" className="scroll-mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">2. 選手を募集</h2><p className="mt-4">受付を開いて保存すると、募集リンクから選手が申し込めます。氏名・写真・競技情報だけをCloudflareに保存します。</p><label className="mt-4 block font-bold">大会の説明<textarea aria-label="大会の説明" className={field} value={data.recruitment?.description||''} onChange={e=>{setData({...data,recruitment:{open:data.recruitment?.open||false,deadline:data.recruitment?.deadline||'',description:e.target.value}});setSaved(false);}}/></label><label className="mt-4 block font-bold">申し込み締切（空欄は締切なし）<input inputMode="numeric" className={field} value={data.recruitment?.deadline||''} placeholder="例: 20271001" onChange={e=>{setData({...data,recruitment:{open:data.recruitment?.open||false,description:data.recruitment?.description||'',deadline:e.target.value.normalize('NFKC')}});setSaved(false);}} onBlur={e=>setData({...data,recruitment:{open:data.recruitment?.open||false,description:data.recruitment?.description||'',deadline:formatDateInput(e.target.value)}})}/></label><label className="mt-4 block"><input type="checkbox" checked={data.recruitment?.open||false} onChange={e=>{setData({...data,recruitment:{open:e.target.checked,deadline:data.recruitment?.deadline||'',description:data.recruitment?.description||''}});setSaved(false);}}/> 申し込みを受け付ける</label>{saved&&data.recruitment?.open&&entryCode&&<a href={'/cloud-entry/?code='+entryCode} className="mt-4 block break-all underline">選手に渡す募集ページを開く</a>}<p className="mt-3">保存前は受付状態を変えません。受付を閉じて保存すると、以前渡したリンクからも申し込めなくなります。</p><a href="/cloud-manage/entry/" className="mt-4 block underline">端末内だけで提出ファイルを作る</a></section>}
  <section id="setup-3" className="scroll-mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">3. 保存を確認</h2><p className="mt-4">{connected?'クラウドへの接続を確認できました。':'接続を確認できていません。'}</p><p className="mt-2">{saved?'大会の保存を確認できました。':'まだ保存していません。'}</p></section>
  <section id="setup-4" className="scroll-mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">4. 選手を読む</h2><p className="mt-4">選手は手入力または会長が持つファイルから登録します。Googleから選手情報は取得しません。</p><a href={link('/cloud-manage/')} className="mt-4 block underline">名簿と写真を登録する</a><details className="mt-4"><summary>Googleの時間設定だけを使う（任意）</summary><p>専用の4列：試合番号・ラウンド数・ラウンド秒・休憩秒。数字だけの表を使います。</p><button disabled={!data||busy} onClick={()=>void importRules()} className="mt-3 rounded-xl border p-3">時間設定だけを読み込む</button><p className="mt-2">{data?.schedule?.length||0}試合分の設定</p></details></section>
  <section id="setup-5" className="scroll-mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">5. 対戦を作る</h2><a href={link('/cloud-manage/')} className="mt-4 block underline">対戦カードを作る</a><p className="mt-3">体重差・同じジム・複数試合の注意を確認して保存します。カード作成後、この画面を読み直して時間を設定します。</p><label className="mt-3 block">ラウンド数<input type="number" min="1" max="20" className={field} value={rounds} onChange={e=>setRounds(Number(e.target.value))}/></label><label className="mt-3 block">1ラウンドの秒数<input type="number" min="10" max="3600" className={field} value={roundSeconds} onChange={e=>setRoundSeconds(Number(e.target.value))}/></label><label className="mt-3 block">休憩の秒数<input type="number" min="0" max="3600" className={field} value={breakSeconds} onChange={e=>setBreakSeconds(Number(e.target.value))}/></label><button disabled={!data?.bouts.length} onClick={()=>{try{const schedule=safeGoogleRules([RULE_HEADERS,...data!.bouts.map((_,i)=>[i+1,rounds,roundSeconds,breakSeconds])]);setData({...data!,schedule,timer:undefined});setSaved(false);setMessage('全試合の時間を設定しました。保存してください。');}catch(error){setMessage(error instanceof Error?error.message:'時間を確認してください。');}}} className="mt-3 rounded-xl border p-3">全試合にこの時間を設定する</button></section>
  <section id="setup-6" className="scroll-mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">6. リンクを渡す</h2><p className="mt-4">当日の画面と準備画面は、同じ大会コードで開きます。管理用リンクは運営者だけに渡してください。</p><a href={link('/cloud-manage/live/')} className="mt-4 block underline">大会当日の画面を開く</a><a href={link('/cloud-manage/')} className="mt-3 block underline">バックアップと復元を開く</a>{data&&<><label className="mt-4 block"><input type="checkbox" checked={data.audience?.open||false} onChange={e=>{setData({...data,audience:{open:e.target.checked}});setSaved(false);}}/> 観客には氏名・所属・体重だけを公開する</label><p className="mt-3">写真・年齢・戦績・意気込み・入場曲は観客へ出しません。保存すると公開状態が変わります。</p>{saved&&data.audience?.open&&entryCode&&<a href={'/cloud-view/?code='+entryCode} className="mt-3 block underline">観客に渡す画面を開く</a>}</>}</section>
  <div className="fixed inset-x-0 bottom-0 z-20 border-t border-slate-200 bg-white p-3 shadow-lg"><div className="mx-auto max-w-4xl"><button disabled={!data||busy} onClick={()=>void save()} className="min-h-14 w-full rounded-xl bg-indigo-700 p-4 text-xl font-black text-white disabled:bg-slate-300">{busy?'確認しています…':'大会をクラウドに保存する'}</button>{message&&<p role="status" className="mt-4 rounded-xl bg-amber-50 p-4">{message}</p>}</div></div></div><p className="mt-4 text-sm">既存の端末内保存は残っています。新しい入口から勝手に移送しません。</p></div></main>;
}
